### ISSUE TITLE
Remove broken links to GO wewbsite

### ISSUE THREAD

**Issue by pgaudet** [oborel/obo-relations#337]
Hello, 

Links that start with 
http://www.geneontology.org/GO.annotation.conventions.shtml#
should be removed from RO; this page has been removed from the GO website.
For example 
http://purl.obolibrary.org/obo/RO_0002326

Thanks, Pascale

**Comment by nlharris** [comment]
http://www.geneontology.org/GO.annotation.conventions.shtml#contributes_to now redirects to http://geneontology.org/docs/go-annotations/ -- is that sufficient?
(Also, is that link even "in" RO, or is it added by Ontobee?)

**Comment by nlharris** [comment]
@pgaudet can we close this issue?

**Comment by cmungall** [comment]
not yet

https://github.com/oborel/obo-relations/search?q=http%3A%2F%2Fwww.geneontology.org%2FGO.annotation.conventions.shtml


but it looks like these may be all derived so fixed on next release?

**Comment by pgaudet** [comment]
@cmungall The link you give send 0 results back - does that mean this is resolved?

**Comment by cmungall** [comment]
![image](https://user-images.githubusercontent.com/50745/148868679-21d49086-27a8-4078-afac-0ad286621cff.png)

try clicking from github you may have some email url warping happening..

**Comment by cmungall** [comment]
we'll do a release on the RO call tomorrow and check after

**Comment by nlharris** [comment]
@balhoff just announced an RO release so I looked at https://github.com/oborel/obo-relations/search?q=http%3A%2F%2Fwww.geneontology.org%2FGO.annotation.conventions.shtml and it looks like in your screenshot. So does that mean this is NOT fixed?

**Comment by matentzn** [comment]
Not only these, also:

http://www.geneontology.org/GO.doc.development.shtml#fate

This fixes this here issue:

https://github.com/oborel/obo-relations/pull/559
